### ISSUE TITLE
Source code for vc_core.pyd requests

### ISSUE THREAD

**Issue by BobH233** [shycats/VirtuCameraBlender#27]
I am trying to use VirtuCamera with Blender 4.1, but the addon is not compatible. My idea is to analyze the communication protocol between the iOS app and the addon, and then try to fix it myself. However, I noticed that the vc_core module is not open source. Could you provide the relevant code for vc_core, or share information about the TCP communication protocol, so that I can help you fix the compatibility issue of the plugin with Blender 4.1?

**Comment by shycats** [comment]
Hello @BobH233 , the plug-in API is closed source and the issue can’t be fixed by only adjusting the communication protocol, it’s also about an incompatibility between the Python version used in latest Blender versions, Cython  and Python Sockets, that makes the plug-in crash. As this required some major refactoring we are working on a new version of the plug-in and App.

**Comment by BobH233** [comment]
Thank you for developing such a great addon! I'm looking forward to your next update！
